src/Entity/SchoolList.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SchoolListRepository")
 */
class SchoolList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="schoolList")
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\School", inversedBy="schoolList", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $school;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $available_seats;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $elected_seats;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SchoolLevel", inversedBy="schoolList", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $school_level;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|user[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(user $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setSchoolList($this);
        }

        return $this;
    }

    public function removeUser(user $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getSchoolList() === $this) {
                $user->setSchoolList(null);
            }
        }

        return $this;
    }

    public function getSchool(): ?school
    {
        return $this->school;
    }

    public function setSchool(school $school): self
    {
        $this->school = $school;

        return $this;
    }

    public function getAvailableSeats(): ?int
    {
        return $this->available_seats;
    }

    public function setAvailableSeats(?int $available_seats): self
    {
        $this->available_seats = $available_seats;

        return $this;
    }

    public function getElectedSeats(): ?int
    {
        return $this->elected_seats;
    }

    public function setElectedSeats(?int $elected_seats): self
    {
        $this->elected_seats = $elected_seats;

        return $this;
    }

    public function getSchoolLevel(): ?SchoolLevel
    {
        return $this->school_level;
    }

    public function setSchoolLevel(SchoolLevel $school_level): self
    {
        $this->school_level = $school_level;

        return $this;
    }
}

src/Form/SchoolListType.php
<?php

namespace App\Form;

use App\Entity\SchoolList;
use App\Entity\User;
use App\Entity\SchoolLevel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class SchoolListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('available_seats', IntegerType::class, array('label'  => 'Nombre de sièges disponibles :'))
            ->add('elected_seats', IntegerType::class, array('label'  => 'Nombre de sièges Les Indépendants :'))
            ->add('school', EntityType::class, array(
                    'label'  => 'Ecole :',
                    'class' => 'App\Entity\School',
                    'choice_label' => 'name'
            ))
            ->add('school_level', EntityType::class, array(
                    'label'  => 'Niveau :',
                    'class' => 'App\Entity\SchoolLevel',
                    'choice_label' => 'name'
            ))
            ->add('user',  EntityType::class, array(
                    'label'  => 'Adhérents :',
                    'class' => 'App\Entity\User',
                    'choice_label' => 'surname' . 'name',
                    'multiple' => true,
                    'expanded' => true,
                    'required' => false
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SchoolList::class,
        ]);
    }
}

src/Controller/SchoolListController.php
<?php

namespace App\Controller;

use App\Entity\SchoolList;
use App\Form\SchoolListType;
use App\Repository\SchoolListRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/school/list")
 */
class SchoolListController extends AbstractController
{
    /**
     * @Route("/", name="school_list_index", methods={"GET"})
     */
    public function index(SchoolListRepository $schoolListRepository): Response
    {
        return $this->render('school_list/index.html.twig', [
            'school_lists' => $schoolListRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="school_list_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $schoolList = new SchoolList();
        $form = $this->createForm(SchoolListType::class, $schoolList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($schoolList);
            $entityManager->flush();

            return $this->redirectToRoute('school_list_index');
        }

        return $this->render('school_list/new.html.twig', [
            'school_list' => $schoolList,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="school_list_show", methods={"GET"})
     */
    public function show(SchoolList $schoolList): Response
    {
        return $this->render('school_list/show.html.twig', [
            'school_list' => $schoolList,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="school_list_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, SchoolList $schoolList): Response
    {
        $form = $this->createForm(SchoolListType::class, $schoolList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('school_list_index', [
                'id' => $schoolList->getId(),
            ]);
        }

        return $this->render('school_list/edit.html.twig', [
            'school_list' => $schoolList,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="school_list_delete", methods={"DELETE"})
     */
    public function delete(Request $request, SchoolList $schoolList): Response
    {
        if ($this->isCsrfTokenValid('delete'.$schoolList->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($schoolList);
            $entityManager->flush();
        }

        return $this->redirectToRoute('school_list_index');
    }
}

templates/school_list/_delete_form.html.twig
<form method="post" action="{{ path('school_list_delete', {'id': school_list.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ school_list.id) }}">
    <button class="btn">Delete</button>
</form>

templates/school_list/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="validation-btn">
    <button class="btn btn-primary">{{ button_label|default('Valider') }}</button>
    </div>
{{ form_end(form) }}

templates/school_list/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SchoolList{% endblock %}

{% block body %}
    <h1>Edit SchoolList</h1>

    {{ include('school_list/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('school_list_index') }}">back to list</a>

    {{ include('school_list/_delete_form.html.twig') }}
{% endblock %}

templates/school_list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SchoolList index{% endblock %}

{% block body %}
    <h1>SchoolList index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Available_seats</th>
                <th>Elected_seats</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for school_list in school_lists %}
            <tr>
                <td>{{ school_list.id }}</td>
                <td>{{ school_list.availableSeats }}</td>
                <td>{{ school_list.electedSeats }}</td>
                <td>
                    <a href="{{ path('school_list_show', {'id': school_list.id}) }}">show</a>
                    <a href="{{ path('school_list_edit', {'id': school_list.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('school_list_new') }}">Create new</a>
{% endblock %}

templates/school_list/new.html.twig
{% extends 'base.html.twig' %}
{% use "admin.html.twig" %}
{% block title %}Liste{% endblock %}

{% block top %}
	{{ parent() }}
{% endblock %}

{% block body %}

<!-- Haut de page -->

	<div class="popular page_section">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title text-center">
						<h1>Liste - CREER</h1>
					</div>
				</div>
			</div>

<!-- Formulaire -->

    <div class="container">
        
        <form class="form-group" method="post">
        {{ include('school_list/_form.html.twig') }}
        </form>
        <br>
        <a href="{{ path('school_list_index') }}">Retour à la liste des listes</a>

     </div>

{% endblock %}

templates/school_list/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SchoolList{% endblock %}

{% block body %}
    <h1>SchoolList</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ school_list.id }}</td>
            </tr>
            <tr>
                <th>Available_seats</th>
                <td>{{ school_list.availableSeats }}</td>
            </tr>
            <tr>
                <th>Elected_seats</th>
                <td>{{ school_list.electedSeats }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('school_list_index') }}">back to list</a>

    <a href="{{ path('school_list_edit', {'id': school_list.id}) }}">edit</a>

    {{ include('school_list/_delete_form.html.twig') }}
{% endblock %}