src/Entity/School.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SchoolRepository")
 */
class School
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $director_gender;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $director_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $director_email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $director_tel;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Kid", mappedBy="school")
     */
    private $kid;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SchoolList", mappedBy="school", cascade={"persist", "remove"})
     */
    private $schoolList;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SchoolClass", mappedBy="school")
     */
    private $school_class;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SchoolLevel", mappedBy="school")
     */
    private $school_level;

    // /**
    //  * @ORM\ManyToOne(targetEntity="App\Entity\File", inversedBy="school")
    //  */
    // private $file;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Document", inversedBy="school")
     */
    private $document;

    public function __construct()
    {
        $this->kid = new ArrayCollection();
        $this->school_class = new ArrayCollection();
        $this->school_level = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(?int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDirectorGender(): ?string
    {
        return $this->director_gender;
    }

    public function setDirectorGender(?string $director_gender): self
    {
        $this->director_gender = $director_gender;

        return $this;
    }

    public function getDirectorName(): ?string
    {
        return $this->director_name;
    }

    public function setDirectorName(?string $director_name): self
    {
        $this->director_name = $director_name;

        return $this;
    }

    public function getDirectorEmail(): ?string
    {
        return $this->director_email;
    }

    public function setDirectorEmail(?string $director_email): self
    {
        $this->director_email = $director_email;

        return $this;
    }

    public function getDirectorTel(): ?string
    {
        return $this->director_tel;
    }

    public function setDirectorTel(?string $director_tel): self
    {
        $this->director_tel = $director_tel;

        return $this;
    }

    /**
     * @return Collection|kid[]
     */
    public function getKid(): Collection
    {
        return $this->kid;
    }

    public function addKid(kid $kid): self
    {
        if (!$this->kid->contains($kid)) {
            $this->kid[] = $kid;
            $kid->setSchool($this);
        }

        return $this;
    }

    public function removeKid(kid $kid): self
    {
        if ($this->kid->contains($kid)) {
            $this->kid->removeElement($kid);
            // set the owning side to null (unless already changed)
            if ($kid->getSchool() === $this) {
                $kid->setSchool(null);
            }
        }

        return $this;
    }

    public function getSchoolList(): ?SchoolList
    {
        return $this->schoolList;
    }

    public function setSchoolList(SchoolList $schoolList): self
    {
        $this->schoolList = $schoolList;

        // set the owning side of the relation if necessary
        if ($this !== $schoolList->getSchool()) {
            $schoolList->setSchool($this);
        }

        return $this;
    }

    /**
     * @return Collection|SchoolClass[]
     */
    public function getSchoolClass(): Collection
    {
        return $this->school_class;
    }

    public function addSchoolClass(SchoolClass $schoolClass): self
    {
        if (!$this->school_class->contains($schoolClass)) {
            $this->school_class[] = $schoolClass;
            $schoolClass->setSchool($this);
        }

        return $this;
    }

    public function removeSchoolClass(SchoolClass $schoolClass): self
    {
        if ($this->school_class->contains($schoolClass)) {
            $this->school_class->removeElement($schoolClass);
            // set the owning side to null (unless already changed)
            if ($schoolClass->getSchool() === $this) {
                $schoolClass->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|SchoolLevel[]
     */
    public function getSchoolLevel(): Collection
    {
        return $this->school_level;
    }

    public function addSchoolLevel(SchoolLevel $schoolLevel): self
    {
        if (!$this->school_level->contains($schoolLevel)) {
            $this->school_level[] = $schoolLevel;
            $schoolLevel->setSchool($this);
        }

        return $this;
    }

    public function removeSchoolLevel(SchoolLevel $schoolLevel): self
    {
        if ($this->school_level->contains($schoolLevel)) {
            $this->school_level->removeElement($schoolLevel);
            // set the owning side to null (unless already changed)
            if ($schoolLevel->getSchool() === $this) {
                $schoolLevel->setSchool(null);
            }
        }

        return $this;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(?File $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getDocument(): ?Document
    {
        return $this->document;
    }

    public function setDocument(?Document $document): self
    {
        $this->document = $document;

        return $this;
    }
}

src/Form/SchoolType.php
<?php

namespace App\Form;

use App\Entity\School;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionResolver\OptionResolver;

class SchoolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array('label'  => 'Nom :'))
            ->add('address', TextType::class, array('label'  => 'Adresse :'))
            ->add('zip_code', IntegerType::class, array('label'  => 'Code Postal :'))
            ->add('city', TextType::class, array('label'  => 'Ville :'))
            ->add('director_gender', ChoiceType::class, array(
                    'choices'  => [
                        'M.' => 'Monsieur',
                        'Mme' => 'Madame',
                    ],
                'label'  => 'Civilité :'))
            ->add('director_name', TextType::class, array('label'  => 'Nom du chef d\'établissement :'))
            ->add('director_email', EmailType::class, array('label'  => 'Email :'))
            ->add('director_tel', TelType::class, array('label'  => 'Téléphone :'))
            // ->add('schoolList')
            // ->add('file')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => School::class,
        ]);
    }
}

src/Controller/SchoolController.php
<?php

namespace App\Controller;

use App\Entity\School;
use App\Form\SchoolType;
use App\Repository\SchoolRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/school")
 */
class SchoolController extends AbstractController
{
    /**
     * @Route("/", name="school_index", methods={"GET"})
     */
    public function index(SchoolRepository $schoolRepository): Response
    {
        return $this->render('school/index.html.twig', [
            'schools' => $schoolRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="school_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $school = new School();
        $form = $this->createForm(SchoolType::class, $school);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($school);
            $entityManager->flush();

            return $this->redirectToRoute('school_index');
        }

        return $this->render('school/new.html.twig', [
            'school' => $school,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="school_show", methods={"GET"})
     */
    public function show(School $school): Response
    {
        return $this->render('school/show.html.twig', [
            'school' => $school,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="school_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, School $school): Response
    {
        $form = $this->createForm(SchoolType::class, $school);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('school_index', [
                'id' => $school->getId(),
            ]);
        }

        return $this->render('school/edit.html.twig', [
            'school' => $school,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="school_delete", methods={"DELETE"})
     */
    public function delete(Request $request, School $school): Response
    {
        if ($this->isCsrfTokenValid('delete'.$school->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($school);
            $entityManager->flush();
        }

        return $this->redirectToRoute('school_index');
    }
}

templates/school/_delete_form.html.twig
<form method="post" action="{{ path('school_delete', {'id': school.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ school.id) }}">
    <button class="btn">Delete</button>
</form>

templates/school/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="validation-btn">
    <button class="btn btn-primary">{{ button_label|default('Valider') }}</button>
    </div>
{{ form_end(form) }}

templates/school/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit School{% endblock %}

{% block body %}
    <h1>Edit School</h1>

    {{ include('school/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('school_index') }}">back to list</a>

    {{ include('school/_delete_form.html.twig') }}
{% endblock %}

templates/school/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}School index{% endblock %}

{% block body %}
    <h1>School index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Address</th>
                <th>Zip_code</th>
                <th>City</th>
                <th>Director_gender</th>
                <th>Director_name</th>
                <th>Director_email</th>
                <th>Director_tel</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for school in schools %}
            <tr>
                <td>{{ school.id }}</td>
                <td>{{ school.name }}</td>
                <td>{{ school.address }}</td>
                <td>{{ school.zipCode }}</td>
                <td>{{ school.city }}</td>
                <td>{{ school.directorGender }}</td>
                <td>{{ school.directorName }}</td>
                <td>{{ school.directorEmail }}</td>
                <td>{{ school.directorTel }}</td>
                <td>
                    <a href="{{ path('school_show', {'id': school.id}) }}">show</a>
                    <a href="{{ path('school_edit', {'id': school.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('school_new') }}">Create new</a>
{% endblock %}

templates/school/new.html.twig
{% extends 'base.html.twig' %}
{% use "admin.html.twig" %}
{% block title %}Etablissement{% endblock %}

{% block top %}
	{{ parent() }}
{% endblock %}

{% block body %}

<!-- Haut de page -->

	<div class="popular page_section">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title text-center">
						<h1>Etablissement - CREER</h1>
					</div>
				</div>
			</div>

<!-- Formulaire -->

    <div class="container">
        
        <form class="form-group" method="post">
        {{ include('school/_form.html.twig') }}
        </form>
        <br>
        <a href="{{ path('school_index') }}">Retour à la liste des établissements</a>

     </div>

{% endblock %}

templates/school/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}School{% endblock %}

{% block body %}
    <h1>School</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ school.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ school.name }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ school.address }}</td>
            </tr>
            <tr>
                <th>Zip_code</th>
                <td>{{ school.zipCode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ school.city }}</td>
            </tr>
            <tr>
                <th>Director_gender</th>
                <td>{{ school.directorGender }}</td>
            </tr>
            <tr>
                <th>Director_name</th>
                <td>{{ school.directorName }}</td>
            </tr>
            <tr>
                <th>Director_email</th>
                <td>{{ school.directorEmail }}</td>
            </tr>
            <tr>
                <th>Director_tel</th>
                <td>{{ school.directorTel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('school_index') }}">back to list</a>

    <a href="{{ path('school_edit', {'id': school.id}) }}">edit</a>

    {{ include('school/_delete_form.html.twig') }}
{% endblock %}