src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Table(name="user")
 * @UniqueEntity(fields="email")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SchoolList", inversedBy="user")
     */
    private $schoolList;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="boolean")
     */
    private $uptodate_membership_fee;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image()
     */
    private $picture;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Kid", inversedBy="parent")
     */
    private $kid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Type("integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $school_list_position;

     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Membership", inversedBy="user")
     */
    // /**
    //  * @ORM\OneToOne(targetEntity="App\Entity\Membership", inversedBy="user", cascade={"persist", "remove"})
    //  * @ORM\JoinColumn(nullable=false)
    //  */
    private $membership;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Board", inversedBy="user")
     */
    // /**
    //  * @ORM\OneToMany(targetEntity="App\Entity\Board", mappedBy="user")
    //  */
    private $board;

    public function __construct()
    {
        $this->kid = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole($role) {
        $this->roles[] = $role;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getSchoolList(): ?SchoolList
    {
        return $this->schoolList;
    }

    public function setSchoolList(?SchoolList $schoolList): self
    {
        $this->schoolList = $schoolList;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getUptodateMembershipFee(): ?bool
    {
        return $this->uptodate_membership_fee;
    }

    public function setUptodateMembershipFee(bool $uptodate_membership_fee): self
    {
        $this->uptodate_membership_fee = $uptodate_membership_fee;

        return $this;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    public function setPicture($picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection|Kid[]
     */
    public function getKid(): Collection
    {
        return $this->kid;
    }

    public function addKid(Kid $kid): self
    {
        if (!$this->kid->contains($kid)) {
            $this->kid[] = $kid;
        }

        return $this;
    }

    public function removeKid(Kid $kid): self
    {
        if ($this->kid->contains($kid)) {
            $this->kid->removeElement($kid);
        }

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(?int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getSchoolListPosition(): ?int
    {
        return $this->school_list_position;
    }

    public function setSchoolListPosition(?int $school_list_position): self
    {
        $this->school_list_position = $school_list_position;

        return $this;
    }

    public function getMembership(): ?Membership
    {
        return $this->membership;
    }

    public function setMembership(Membership $membership): self
    {
        $this->membership = $membership;

        return $this;
    }

    /**
     * @return Collection|Board[]
     */
    public function getBoard(): Collection
    {
        return $this->board;
    }

    public function addBoard(Board $board): self
    {
        if (!$this->board->contains($board)) {
            $this->board[] = $board;
            $board->setUser($this);
        }

        return $this;
    }

    public function removeBoard(Board $board): self
    {
        if ($this->board->contains($board)) {
            $this->board->removeElement($board);
            // set the owning side to null (unless already changed)
            if ($board->getUser() === $this) {
                $board->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Membership;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionResolver\OptionResolver;
use App\Form\KidType;
// use App\Form\MembershipType;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, array('label'  => 'Email :'))
            // ->add('roles')
            ->add('password', PasswordType::Class, array('label'  => 'Mot de passe :'))
            ->add('name', TextType::class, array('label'  => 'Nom :'))
            ->add('surname', TextType::class, array('label'  => 'Prénom :'))
            ->add('tel', TelType::class, array('label'  => 'Téléphone :'))
            // ->add('uptodate_membership_fee', HiddenType::class, array('data'  => 'NON'))
            
            // UPLOAD PICTURE NE FONCTIONNE PAS A CAUSE DU POIDS DES IMAGES TROP LOURD (Bug symfony 4.2)
            ->add('picture', FileType::class, array(
                'label' => 'Photo :',
                'required'=>null,
                'attr' => ['placeholder' => 'Choisir une photo'],
                'data_class' => null))
            // ->add('picture', FileType::class, array(
            //     'label' => 'Photo :',
            //     'attr' => ['placeholder' => 'Choisir une photo']
            //     ))
            ->add('address', TextType::class, array('label'  => 'Adresse :'))
            ->add('zip_code',IntegerType::class, array('label'  => 'Code Postal :'))
            ->add('city', TextType::class, array('label'  => 'Ville :'))
            // ->add('school_list_position')
            // ->add('schoolList')
            ->add('membership', EntityType::class, array(
                    'label'  => 'Type Adhésion :',
                    'class' => 'App\Entity\Membership',
                    'choice_label' => 'type',
                    'required' => false))
            ->add('kid', CollectionType::class, array(
                    'label'  => 'Enfant :',
                    'entry_type' => KidType::class,
                    'allow_add'=> true,
                    'allow_delete' => true
            ))
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $user = $form->getData();
            // var_dump($user);
            $password = $passwordEncoder->encodePassword($user, $user->getPassword());
            $user->setPassword($password);
            $user->addRole("ROLE_USER");

            $user->setUptodateMembershipFee(false);

            // NE FONCTIONN PAS we upload the picture file and name it with the new user name
            
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $user->getPicture();
            $file = $form->get('picture')->getData();
            // var_dump($file);
            $fileName = $user->getSurname().'_'.$user->getName().'.'.$file->guessExtension();
            // $fileName = $user->getSurname().'_'.$user->getName().'.jpeg';

            //moves the file to the directory where images are stored
            $file->move(
                $this->getParameter('pictures_directory'),
                $fileName
            );
            //updates the 'Picture' property to store the JPEG file name
            //instead of its contents
            $user->setPicture($fileName);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success', 'Votre compte à bien été enregistré.');
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index', [
                'id' => $user->getId(),
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
  $(document).ready(function() {
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#user_kid');

    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;
    
    // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
    $('#add_kid').click(function(e) {
      addKid($container);

      e.preventDefault(); // évite qu'un # apparaisse dans l'URL
      return false;
    });

    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'un nouveau membre par exemple).
    {# if (index == 0) {
      addKid($container);
    } else {
      // S'il existe déjà des enfants, on ajoute un lien de suppression pour chacune d'entre elles
      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    } #}

    // La fonction qui ajoute un formulaire KidType
    function addKid($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var template = $container.attr('data-prototype')
        .replace(/__name__label__/g, 'Enfant n°' + (index+1))
        .replace(/__name__/g,        index)
      ;

      // On crée un objet jquery qui contient ce template
      var $prototype = $(template);

      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);

      // On ajoute le prototype modifié à la fin de la balise <div>
      $container.append($prototype);

      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }

    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      var $deleteLink = $('<a href="#" class="btn btn-danger">Désincrire</a>');

      // Ajout du lien
      $prototype.append($deleteLink);

      // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
      $deleteLink.click(function(e) {
        $prototype.remove();

        e.preventDefault(); // évite qu'un # apparaisse dans l'URL
        return false;
      });
    }
  });
</script>


{{ form_start(form) }}
  
    {{ form_widget(form) }}
        {{ form_row(form.kid) }}
        <a href="#" id="add_kid" class="btn btn-secondary">Inscrire un enfant</a>
        
    <br>
    <br>
    <div class="validation-btn">
    <button class="btn btn-primary">{{ button_label|default('Valider') }}</button>
    </div>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}
{% use "adhesion.html.twig" %}
{% block title %}Adhérent{% endblock %}

{% block top %}
	{{ parent() }}
{% endblock %}

{% block body %}

<!-- Haut de page -->

	<div class="popular page_section">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title text-center">
						<h1>Adhérent - LISTE</h1>
					</div>
				</div>
			</div>

<!-- Formulaire -->

    <div class="container">

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Tel</th>
                <th>Uptodate_membership_fee</th>
                <th>Picture</th>
                <th>Address</th>
                <th>Zip_code</th>
                <th>City</th>
                <th>School_list_position</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.surname }}</td>
                <td>{{ user.tel }}</td>
                <td>{{ user.uptodateMembershipFee ? 'Yes' : 'No' }}</td>
                <td>{{ user.picture }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.zipCode }}</td>
                <td>{{ user.city }}</td>
                <td>{{ user.schoolListPosition }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>

    </div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}
{% use "adhesion.html.twig" %}
{% block title %}Adhérent{% endblock %}

{% block top %}
	{{ parent() }}
{% endblock %}

{% block body %}

<!-- Haut de page -->

	<div class="popular page_section">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title text-center">
						<h1>Adhérent - CREER UN PROFIL</h1>
					</div>
				</div>
			</div>

<!-- Formulaire -->

    <div class="container">
        
        <form class="form-group" method="post">
        {{ include('user/_form.html.twig') }}
        </form>
        <br>
        <a href="{{ path('user_index') }}">Retour à la liste des adhérents</a>

     </div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}
{% use "adhesion.html.twig" %}
{% block title %}Adhérent{% endblock %}

{% block top %}
	{{ parent() }}
{% endblock %}

{% block body %}

<!-- Haut de page -->

	<div class="popular page_section">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title text-center">
						<h1>Adhérent - PROFIL</h1>
					</div>
				</div>
			</div>

<!-- Formulaire -->

    <div class="container">

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ user.surname }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ user.tel }}</td>
            </tr>
            <tr>
                <th>Uptodate_membership_fee</th>
                <td>{{ user.uptodateMembershipFee ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ user.picture }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ user.address }}</td>
            </tr>
            <tr>
                <th>Zip_code</th>
                <td>{{ user.zipCode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ user.city }}</td>
            </tr>
            <tr>
                <th>School_list_position</th>
                <td>{{ user.schoolListPosition }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">Retour à la liste des adhérents</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">Modifier</a>

    {{ include('user/_delete_form.html.twig') }}

      </div>

{% endblock %}